name: aqar_zone_flutter_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  awesome_dialog: ^3.2.1
  lottie: ^3.1.3
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lang/

